### ISSUE TITLE
XmlLoadDocument load big file too slow

### ISSUE THREAD

**Issue by fjocean** [netcwmp/netcwmp#3]
I use XmlLoadDocument to load a big xml file about 464K, it takes a long time. then I use gprof to monitoring what takes the time and find pool_pfree is called many times and takes about 99.68% time of the whole program.

PS:
attachment CPE_000295_0000279768.zip is the big xml file.

gprof_result.zip is the result of using gprof monitoring.

[CPE_000295_0000279768.zip](https://github.com/netcwmp/netcwmp/files/643584/CPE_000295_0000279768.zip)
[gprof_result.zip](https://github.com/netcwmp/netcwmp/files/643586/gprof_result.zip)

**Comment by feilaoda** [comment]
@fjocean 
You can change the pool alloc size in libpool/include/cwmp/pool.h
#define POOL_MAX_ALLOC_FROM_POOL  (1024 - 1)
#define POOL_DEFAULT_SIZE    (1024)

to 

#define POOL_MAX_ALLOC_FROM_POOL  (1024*10 - 1)
#define POOL_DEFAULT_SIZE    (1024*10)

**Comment by fjocean** [comment]
okay, thanks
